# Project information
site_name: Data Science Interview preparation
site_author: Kuldeep Singh Sidhu
site_description: >-
  This is a completely open-source platform for
  maintaining curated list of interview questions
  and answers for people looking and preparing
  for data science opportunities.

# Repository
repo_name: singhsidhukuldeep/singhsidhukuldeep.github.io
repo_url: https://github.com/singhsidhukuldeep/singhsidhukuldeep.github.io

extra:
  generator: false

  social:
    - icon: octicons/mark-github-16
      link: https://github.com/singhsidhukuldeep/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/singhsidhukuldeep
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/kuldeep_s_s
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/u/7182350/
    - icon: octicons/globe-16
      link: http://kuldeepsinghsidhu.com

  analytics:
    provider: google
    property: G-EVGNTG49J7

  consent:
    title: Cookie Consent <br><small>Help Us ✌️, Help You 🫵</small>
    actions:
      - accept
      - manage
    cookies:
      analytics:
        name: Google
        checked: true
      github:
        name: GitHub
        checked: true
    description: >- 
      We use cookies to recognize your repeated visits and preferences, improve and offer better services🤗
      <br>
      With your consent🤝, you're helping us to give you better experience. 
      <br>
      <a herf="https://singhsidhukuldeep.github.io/privacy">Read about privacy policy here<a>

theme:
  name: material
  custom_dir: overrides

  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - navigation.instant.progress
    - navigation.path
    - navigation.top

  icon:
    logo: fontawesome/solid/terminal
    repo: fontawesome/brands/git-alt
#  favicon: fontawesome/solid/terminal

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: purple
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: purple
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
#plugins
plugins:
  # - optimize
  - search:
      lang:
        - en
  # - privacy:
      # cache: false
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
  - mkdocs-jupyter: #https://github.com/danielfrg/mkdocs-jupyter
      execute: false
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_logo: https://repository-images.githubusercontent.com/275878203/13719500-bb75-11ea-8f3a-be2ffb87a6a2
      copyright: Copyright © 2020 - 2024 Kuldeep Singh Sidhu
      cover_title: The Data Science Book
      cover_subtitle: https://singhsidhukuldeep.github.io
      output_path: /workspace/singhsidhukuldeep.github.io/pdf_output/DataScience.pdf
      back_cover: true

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - meta
  - codehilite

# Page tree
nav:
  - 🏡 Home: index.md

  - 📅 Suggested Learning Paths: Suggested-Learning-Paths.md

  - 👨🏾‍💻 Online Resources:
      - Online Study Material: Online-Material/Online-Material-for-Learning.md
      - Popular Blogs: Online-Material/popular-resouces.md

  - 🚴🏽‍♀ As fast as possible:
      - Introduction: as-fast-as-possible/index.md
      - Neural Networks: as-fast-as-possible/Neural-Networks.md
      - Deep Natural Language Processing: as-fast-as-possible/Deep-NLP.md
      - Deep Computer Vision: as-fast-as-possible/Deep-CV.md
      - Tensorflow 2 with Keras: as-fast-as-possible/TF2-Keras.md

  - ‍🎓 ML Topics:
      - Machine-Learning\ARIMA.md
      - Machine-Learning\Activation functions.md
      - Machine-Learning\Collaborative Filtering.md
      - Machine-Learning\Confusion Matrix.md
      - Machine-Learning\DBSCAN.md
      - Machine-Learning\Decision Trees.md
      - Machine-Learning\Gradient Boosting.md
      - Machine-Learning\K-means clustering.md
      - Machine-Learning\Linear Regression.md
      - Machine-Learning\Logistic Regression.md
      - Machine-Learning\Loss Function MAE, RMSE.md
      - Machine-Learning\Neural Networks.md
      - Machine-Learning\Normal Distribution.md
      - Machine-Learning\Normalization Regularisation.md
      - Machine-Learning\Overfitting, Underfitting.md
      - Machine-Learning\PCA.md
      - Machine-Learning\Random Forest.md
      - Machine-Learning\Support Vector Machines.md
      - Machine-Learning\Unbalanced, Skewed data.md
      - Machine-Learning\kNN.md

  - 📝 Cheat Sheets:
      - Python: Cheat-Sheets/Python.md
      - NumPy: Cheat-Sheets/NumPy.md
      - Pandas: Cheat-Sheets/Pandas.md
      - Scikit Learn: Cheat-Sheets/Sk-learn.md
      - Keras: Cheat-Sheets/Keras.md
      - PyTorch: Cheat-Sheets/PyTorch.md
      - TensorFlow: Cheat-Sheets/tensorflow.md
      - SQL: Cheat-Sheets/SQL.md
      - Regular Expressions (RegEx): Cheat-Sheets/RegEx.md
      - Flask: Cheat-Sheets/Flask.md
      - Django: Cheat-Sheets/Django.md
      - PySpark: Cheat-Sheets/PySpark.md
      - Hypothesis Tests: Cheat-Sheets/Hypothesis-Tests.md

  - 🎌 Deploying ML Models:
      - Production Deployment: Deploying-ML-models/deploying-ml-models.md

  - 👨🏿‍🏫 Interview Questions:
      - Software Development:
          - DSA (Data Structures & Algorithms): Interview-Questions/data-structures-algorithms.md
          - System Design: Interview-Questions/System-design.md
      - Natural Language Processing (NLP): Interview-Questions/Natural-Language-Processing.md
      - Probability: Interview-Questions/Probability.md

  - 📳 Projects: projects.md

  - <small>Privacy Policy</small>: privacy.md
  - <small>Contact</small>: contact.md

# Copyright
copyright: Copyright &copy; 2020 - <script>document.write(/\d{4}/.exec(Date())[0])</script> <strong>Kuldeep Singh Sidhu</strong>
